apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  name: machinemetrics
  namespace: factory
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: machinemetrics
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: machinemetrics
        redeploy: "1638344201"
    spec:
      containers:
      - env:
        - name: BROKER_URL
          value: broker-service-hdls-svc
        - name: BROKER_PORT
          value: "61616"
        image: quay.io/jules0/qiot-manufacturing-factory-machinemetrics
        imagePullPolicy: Always
        name: machinemetrics
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
