apiVersion: apps/v1
kind: Deployment
metadata:
  name: machinemetrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machinemetrics
  template:
    metadata:
      labels:
        app: machinemetrics 
    spec:
      containers:
      - name: machinemetrics
        image: quay.io/jules0/qiot-manufacturing-factory-machinemetrics
